from __future__ import annotations
"""
Validates and normalises the JSON case generated by Gemini.
Raises ValueError with a descriptive message if the case is malformed.
"""


def validate_case(case: dict) -> dict:
    """
    Validates structure and logical consistency.
    Returns the normalised case dict on success.
    Raises ValueError on failure (caller should retry generation).
    """
    _require_keys(case, ["setting", "victim", "twist", "murderer", "red_herring", "suspects", "clues", "solution"])
    _require_keys(case["setting"], ["genre", "era", "venue", "atmosphere"])
    _require_keys(case["victim"], ["name", "gender", "background", "secrets"])

    suspects = case["suspects"]
    if len(suspects) != 6:
        raise ValueError(f"Expected 6 suspects, got {len(suspects)}")

    names = [s["name"] for s in suspects]

    # Murderer and red herring must reference actual suspects
    if case["murderer"] not in names:
        raise ValueError(f"murderer '{case['murderer']}' not in suspect list")
    if case["red_herring"] not in names:
        raise ValueError(f"red_herring '{case['red_herring']}' not in suspect list")
    if case["murderer"] == case["red_herring"]:
        raise ValueError("murderer and red_herring cannot be the same suspect")

    for s in suspects:
        _require_keys(s, ["name", "gender", "relation", "motive", "trait", "last_seen", "alibi"])

    # Normalise is_murderer / is_red_herring flags (Gemini sometimes forgets)
    for s in suspects:
        s["is_murderer"]   = (s["name"] == case["murderer"])
        s["is_red_herring"]= (s["name"] == case["red_herring"])

    # Validate clue structure
    clues = case["clues"]
    _require_keys(clues, ["opening", "round_1", "round_2", "round_3", "round_4"])
    if len(clues["opening"]) != 3:
        raise ValueError(f"Expected 3 opening clues, got {len(clues['opening'])}")
    for clue in clues["opening"]:
        _require_keys(clue, ["type", "text"])
    for key in ["round_1", "round_2", "round_3", "round_4"]:
        _require_keys(clues[key], ["type", "text"])

    if not case.get("solution"):
        raise ValueError("solution field is empty")

    return case


def _require_keys(d: dict, keys: list[str]) -> None:
    missing = [k for k in keys if k not in d]
    if missing:
        raise ValueError(f"Missing keys {missing} in: {list(d.keys())}")
