from __future__ import annotations
"""
Case reveal phase — posts the full crime scene, suspect profiles, and opening clues.

Key design decisions:
- Suspect profiles are shown in a single paginated message (SuspectFilesView) instead of
  6 individual embeds. This cuts the opening message flood from 11+ to ~5 messages.
- Message jump_urls for crime scene, suspects, and clues are stored in state.ref_urls so
  round embeds can surface them as quick-reference links.
"""
import discord
from game.state import GameState
from game import session_manager
from bot.views.suspect_view import SuspectFilesView


CLUE_TYPE_EMOJI = {
    "physical":    "🔍",
    "timeline":    "⏱️",
    "testimonial": "👁️",
    "forensic":    "🧪",
    "documentary": "📄",
}

CLUE_TYPE_LABEL = {
    "physical":    "Physical Evidence",
    "timeline":    "Timeline Evidence",
    "testimonial": "Witness Testimony",
    "forensic":    "Forensic Evidence",
    "documentary": "Documentary Evidence",
}


def _roster_list(suspects: list[dict]) -> str:
    """
    Mobile-friendly suspect list — one line per suspect, no fixed-width columns.
    """
    lines = []
    for i, s in enumerate(suspects, 1):
        lines.append(f"**{i}. {s['name']}** — {s['relation']} · *{s['last_seen']}*")
    lines.append("\n*One of them committed the murder.*")
    return "\n".join(lines)


async def run_reveal(channel: discord.TextChannel, state: GameState) -> None:
    state.phase = "REVEAL"

    # ── 0. Case intro ────────────────────────────────────────────────────────
    player_names = " · ".join(p.display_name for p in state.players.values())
    intro_embed  = discord.Embed(
        title="📂  CASE FILE UNSEALED",
        description=(
            f"Detectives: **{player_names}**\n\n"
            "Your assignment has arrived. Read every detail carefully — "
            "the killer has already covered their tracks. "
            "You have 4 rounds of clues and one final guess to bring them to justice.\n\n"
            "⚠️ *Every case contains a **Plottwyst** — a deliberate misdirection woven into the evidence. "
            "The opening clues may not point where you think.*"
        ),
        color=discord.Color.dark_grey(),
    )
    intro_embed.set_footer(text="Tip: Use /howtoplay if this is your first case.")
    await channel.send(embed=intro_embed)

    # ── 1. Crime scene ──────────────────────────────────────────────────────
    scene   = state.case
    victim  = scene["victim"]
    setting = scene["setting"]

    scene_embed = discord.Embed(
        title="🔴  A MURDER HAS BEEN COMMITTED",
        description=setting["atmosphere"],
        color=discord.Color.dark_red(),
    )
    scene_embed.add_field(
        name="📍  Location",
        value=f"*{setting['venue']}*  ·  {setting['era']}",
        inline=False,
    )
    scene_embed.add_field(
        name="💀  Victim",
        value=f"**{victim['name']}**  —  {victim['background']}",
        inline=False,
    )
    scene_embed.set_footer(text=f"Genre: {setting['genre'].title()}  ·  Case generated by Plottwyst")
    scene_msg = await channel.send(embed=scene_embed)
    state.ref_urls["scene"] = scene_msg.jump_url

    # ── 2. Suspect roster + paginated profile viewer ─────────────────────────
    suspects = scene["suspects"]
    total    = len(suspects)

    # At-a-glance list — mobile-friendly, no fixed-width columns
    roster_embed = discord.Embed(
        title="🕵️  SUSPECT PROFILES",
        description=(
            f"**{total} suspects identified.** Use ◀ ▶ below to read full profiles.\n\n"
            + _roster_list(suspects)
        ),
        color=discord.Color.dark_gold(),
    )
    roster_embed.set_footer(text="Scroll back here anytime — or use the Quick Reference links in round embeds.")
    roster_msg = await channel.send(embed=roster_embed)
    state.ref_urls["suspects"] = roster_msg.jump_url

    # Paginated interactive viewer — one message, all 6 profiles, ◀ ▶ to flip
    suspect_view = SuspectFilesView(suspects)
    suspect_msg  = await channel.send(embed=suspect_view.build_embed(), view=suspect_view)
    state.ref_urls["profiles"] = suspect_msg.jump_url

    # ── 3. Opening clues ────────────────────────────────────────────────────
    opening_clues = scene["clues"]["opening"]
    total_clues   = len(opening_clues)

    clue_embed = discord.Embed(
        title="🔎  INITIAL EVIDENCE",
        description=(
            f"**{total_clues} piece{'s' if total_clues != 1 else ''} of evidence** "
            "collected at the scene. More will emerge after each voting round."
        ),
        color=discord.Color.teal(),
    )
    for i, clue in enumerate(opening_clues, 1):
        emoji      = CLUE_TYPE_EMOJI.get(clue["type"], "📌")
        type_label = CLUE_TYPE_LABEL.get(clue["type"], clue["type"].upper())
        clue_embed.add_field(
            name=f"{emoji}  Clue {i}  —  {type_label}",
            value=clue["text"],
            inline=False,
        )
        state.revealed_clues.append(clue)

    clue_embed.set_footer(text="Tip: Note which suspects these clues implicate or alibi.")
    clues_msg = await channel.send(embed=clue_embed)
    state.ref_urls["clues"] = clues_msg.jump_url

    # ── 4. Initialise remaining suspects & clue pool ─────────────────────────
    state.remaining_suspects = [s["name"] for s in suspects]
    state.clue_pool          = list(scene["clue_pool"])

    await session_manager.save(state)
